"use client";
import {useEffect,useRef,useState} from "react";
export type Receipt={id:string;token:string};
export default function OrderConfirmation({receipt,onClose,note}:{receipt:Receipt;onClose:()=>void;note?:string}){
 const dialog=useRef<HTMLDialogElement>(null),[copied,setCopied]=useState(""),[url,setUrl]=useState("");
 const path="/order/"+receipt.id+"#"+receipt.token;
 useEffect(()=>{setUrl(location.origin+path);const node=dialog.current;const previous=document.activeElement as HTMLElement|null;node?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{node?.close();document.body.style.overflow=overflow;previous?.focus();};},[path]);
 return <dialog ref={dialog} className="orderConfirmation" aria-labelledby="confirmation-title" onCancel={onClose} onClose={onClose}><button className="confirmationClose" type="button" aria-label="Close order confirmation" onClick={onClose}>×</button><span className="confirmationCheck" aria-hidden="true">✓</span><p className="eyebrow">ORDER #{receipt.id.slice(0,8).toUpperCase()}</p><h2 id="confirmation-title">Your meal is on its way to the kitchen.</h2><p>Your order is confirmed. Follow its progress with your private tracking link.</p><a className="button" href={path}>Track your order →</a><label>Save your tracking link<input readOnly value={url} onFocus={e=>e.target.select()}/></label><button className="outline" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(url);setCopied("Tracking link copied.");}catch{setCopied("Select and copy the link above to save it.");}}}>Copy tracking link</button><p className="confirmationHint">Keep this link, especially if you ordered as a guest. You can reopen your latest order from this storefront on this device. Anyone with the link can view your order and submit its review.</p>{copied&&<p role="status">{copied}</p>}{note&&<p role="status">{note}</p>}<button className="outline" type="button" onClick={onClose}>Continue browsing</button></dialog>;
}
