"use client";
import { useState } from "react";
import PublicFooter from "./components/PublicFooter";

const dishes = [{name:"Butter chicken",price:"₹420",category:"Mains"},{name:"Dal makhani",price:"₹310",category:"Mains"},{name:"Amritsari fish",price:"₹490",category:"Starters"}];
export default function Home() {
  const [selected,setSelected] = useState(0);
  return <main className="marketingHome">
    <div className="announcement">Made for independent restaurants. Built for direct orders.</div>
    <section className="landingHero">
      <div className="landingHeroCopy"><p className="brandScript">Your kitchen. Your people.</p><h1>Great food deserves<br/>a place of its own.</h1><div className="brandRule" aria-hidden="true">✧</div><p>Your restaurant, beautifully online. Give diners a direct way to discover your menu, place an order, and come back for more.</p><div className="landingActions"><a className="button" href="/start">Start for free <span aria-hidden="true">→</span></a><a className="textLink" href="/how-it-works">See how it works</a></div><small>Your menu. Your brand. Your customer relationships.</small></div>
      <div className="restaurantPreview" aria-label="Example restaurant storefront"><div className="previewTop"><span>THE SAFFRON TABLE</span><small>EXAMPLE STOREFRONT</small></div><div className="previewPlate" aria-hidden="true"><svg viewBox="0 0 260 260" fill="none"><circle cx="130" cy="130" r="113" fill="#f8f0e2"/><circle cx="130" cy="130" r="89" stroke="#d6c7ac"/><circle cx="130" cy="130" r="72" fill="#b7471d"/><path d="M87 113c30-38 77-15 87 19-33 32-74 36-87-19" fill="#e6aa61"/><path d="M115 69c-20 21-13 38 11 39 16-18 9-32-11-39M172 146c-24 6-31 24-15 38 24-2 27-21 15-38" fill="#687547"/><path d="m106 133 38-24m-20 43 32-20" stroke="#fff4db" strokeWidth="6" strokeLinecap="round"/></svg><span>Good food.<br/><em>Closer to home.</em></span></div><div className="previewMenu"><div><small>FROM OUR KITCHEN</small><h2>{dishes[selected].name}</h2><p>{dishes[selected].category} <b>{dishes[selected].price}</b></p></div><div className="previewChoices" role="group" aria-label="Preview a dish">{dishes.map((dish,index)=><button key={dish.name} aria-pressed={selected===index} onClick={()=>setSelected(index)}>{dish.name}</button>)}</div></div></div>
    </section>
    <div className="productPromises"><span>YOUR OWN STOREFRONT</span><i aria-hidden="true">✧</i><span>PICKUP & DELIVERY ORDERS</span><i aria-hidden="true">✧</i><span>ONE SIMPLE DASHBOARD</span></div>
    <section className="landingStory"><p className="brandScript">A little less distance</p><h2>Between your kitchen<br/>and their table.</h2><div className="brandRule" aria-hidden="true">✧</div><p>Make ordering feel as welcoming as walking through your door. Plated brings your menu, restaurant story, and daily operations together.</p><div className="landingFeatureGrid"><article><span>01</span><h3>Make it yours</h3><p>Your logo, cover photo, menu images, and story. A storefront with your restaurant at the center.</p></article><article><span>02</span><h3>Keep orders moving</h3><p>Accept orders, update preparation status, and give diners a private link to follow their meal.</p></article><article><span>03</span><h3>Stay connected</h3><p>Collect reviews from completed orders and reply to your guests from the owner dashboard.</p></article></div></section>
    <section className="landingOperations"><div><p className="brandScript">Behind every good service</p><h2>A calmer way<br/>to run your kitchen.</h2><p>Update dishes, organize categories, pause ordering, and manage pickup or delivery from one place.</p><a className="textLink" href="/features">Explore the features →</a></div><div className="operationsPreview" aria-label="Example order workflow"><p className="eyebrow">FROM ORDER TO TABLE</p>{["New order received","Your kitchen is preparing","Ready for your guest"].map((label,index)=><div key={label}><b>0{index+1}</b><span>{label}</span><i aria-hidden="true">{index===2?"✓":"→"}</i></div>)}<small>Guests can follow each update from their private order link.</small></div></section>
    <section className="brandCta"><p className="brandScript">Your table is waiting</p><h2>Let’s put your restaurant<br/>on the menu.</h2><a className="button" href="/start">Build my restaurant site →</a></section>
    <PublicFooter />
  </main>;
}
