"use client";
import {useEffect,useState} from "react";
import {ApiError,responseJson} from "../../lib/api-client";
import {CustomerAccount,SavedAddress} from "../../lib/customer";
import {money} from "../../lib/orders";
const emptyAddress={label:"Home",recipient:"",phone:"",address:""};
export default function Profile({store}:{store?:string}){
 const [account,setAccount]=useState<CustomerAccount|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[signedOut,setSignedOut]=useState(false),[revision,setRevision]=useState(0);
 const [draft,setDraft]=useState<Partial<SavedAddress>|null>(null);
 useEffect(()=>{const controller=new AbortController();fetchResponse().then(response=>responseJson<CustomerAccount>(response)).then(result=>{if(!controller.signal.aborted){setAccount(result);setError("");}}).catch(cause=>{if(!controller.signal.aborted){setSignedOut(cause instanceof ApiError&&cause.status===401);setError(cause.message);}});async function fetchResponse(){return await fetch("/api/profile",{signal:controller.signal});}return()=>controller.abort();},[revision]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),4000);return()=>clearTimeout(timer);},[notice]);
 async function save(url:string,method:string,body:unknown){setBusy(true);setError("");try{await responseJson(await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}));setNotice("Changes saved.");setRevision(x=>x+1);return true;}catch(cause){setError(cause instanceof Error?cause.message:"Please retry.");return false;}finally{setBusy(false);}}
 return <main className="customerProfile"><div className="profileHeading"><p className="brandScript">Your place at the table</p><h1>Your profile</h1><p>Keep your contact details and delivery addresses ready for your next meal.</p>{store&&<a href={"/r/"+store}>← Back to the menu</a>}</div>
 {error&&<p className="formError" role="alert">{error} {signedOut?<a href={"/sign-in"+(store?"?store="+encodeURIComponent(store):"")}>Sign in</a>:<button onClick={()=>setRevision(x=>x+1)}>Retry</button>}</p>}{notice&&<p className="profileNotice" role="status">{notice}</p>}
 {!account&&!error&&<p role="status">Loading your profile…</p>}
 {account&&<><section className="panel"><h2>Contact details</h2><form className="menuEditor" onSubmit={async e=>{e.preventDefault();await save("/api/profile","PUT",account.profile);}}><fieldset disabled={busy}><label>Your name<input required maxLength={100} autoComplete="name" value={account.profile.name} onChange={e=>setAccount({...account,profile:{...account.profile,name:e.target.value}})}/></label><label>Phone number<input type="tel" maxLength={25} autoComplete="tel" value={account.profile.phone} onChange={e=>setAccount({...account,profile:{...account.profile,phone:e.target.value}})}/></label><button className="button">Save contact details</button></fieldset></form></section>
 <section className="panel"><div className="profileSectionHeading"><h2>Delivery addresses</h2><button className="button" disabled={busy} onClick={()=>setDraft({...emptyAddress,recipient:account.profile.name,phone:account.profile.phone})}>Add address</button></div><p>Choose any saved address at checkout. Changes here won’t change orders already placed.</p><div className="addressGrid">{account.addresses.map(address=><article key={address.id}><h3>{address.label}</h3><b>{address.recipient}</b><p>{address.address}</p><p>{address.phone}</p><div className="formActions"><button className="outline" disabled={busy} onClick={()=>setDraft(address)}>Edit {address.label}</button><button className="outline" disabled={busy} onClick={()=>save("/api/profile/addresses","DELETE",{id:address.id})}>Remove {address.label}</button></div></article>)}</div>{!account.addresses.length&&<p>No saved addresses yet. Add home, work, or anywhere you like to eat.</p>}
 {draft&&<form className="menuEditor addressEditor" onSubmit={async e=>{e.preventDefault();if(await save("/api/profile/addresses",draft.id?"PATCH":"POST",draft))setDraft(null);}}><h3>{draft.id?"Edit address":"New address"}</h3><fieldset disabled={busy}><label>Address label<input required maxLength={40} value={draft.label||""} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label>Recipient name<input required maxLength={100} value={draft.recipient||""} onChange={e=>setDraft({...draft,recipient:e.target.value})}/></label><label>Phone<input required type="tel" maxLength={25} value={draft.phone||""} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Full delivery address<textarea required minLength={10} maxLength={500} value={draft.address||""} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><div className="formActions"><button className="button">Save address</button><button type="button" className="outline" onClick={()=>setDraft(null)}>Cancel</button></div></fieldset></form>}</section>
 <section id="orders" className="panel"><h2>Your orders</h2><p>Your latest 100 orders placed while signed in. Guest orders stay accessible through their private tracking links.</p><div className="profileOrders">{account.orders.map(order=><a key={order.id} href={"/order/"+order.id+"#"+order.tracking_token}><span><b>{order.restaurant_name}</b><small>{new Date(order.created_at).toLocaleString()} · #{order.id.slice(0,8).toUpperCase()}</small></span><span>{money(order.total)}<small>{order.status} →</small></span></a>)}</div>{!account.orders.length&&<p>Your next meal will start your order history.</p>}</section></>}
 </main>;
}
