import { createClient } from "@libsql/client";
import { randomUUID } from "crypto";
const db = createClient({ url: process.env.DATABASE_URL || "file:plated.db" });
let ready: Promise<void> | undefined;
async function initialise() { await db.batch(["CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL)","CREATE TABLE IF NOT EXISTS restaurants (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT NOT NULL, theme TEXT NOT NULL, created_at TEXT NOT NULL)","CREATE TABLE IF NOT EXISTS menu_items (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL, name TEXT NOT NULL, price INTEGER NOT NULL, category TEXT NOT NULL, rating REAL NOT NULL DEFAULT 0, rating_count INTEGER NOT NULL DEFAULT 0)","CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, restaurant_id TEXT NOT NULL, customer_name TEXT NOT NULL, total INTEGER NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL)"]); }
async function ensure() { ready ??= initialise(); await ready; }
export async function findUser(email: string) { await ensure(); const result = await db.execute({ sql: "SELECT id, name, email, password_hash FROM users WHERE email = ?", args: [email.toLowerCase()] }); return result.rows[0] as unknown as { id: string; name: string; email: string; password_hash: string } | undefined; }
export async function createUser(name: string, email: string, passwordHash: string) { await ensure(); const user = { id: randomUUID(), name, email: email.toLowerCase() }; await db.execute({ sql: "INSERT INTO users (id, name, email, password_hash, created_at) VALUES (?, ?, ?, ?, ?)", args: [user.id, user.name, user.email, passwordHash, new Date().toISOString()] }); return user; }
export async function createRestaurant(ownerId:string,name:string,slug:string,description:string,theme:string){await ensure();const restaurant={id:randomUUID(),ownerId,name,slug,description,theme};await db.execute({sql:"INSERT INTO restaurants (id, owner_id, name, slug, description, theme, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",args:[restaurant.id,ownerId,name,slug,description,theme,new Date().toISOString()]});for(const item of [{name:"Butter Chicken",price:420,category:"Mains",rating:4.9,ratingCount:126},{name:"Dal Makhani",price:310,category:"Mains",rating:4.8,ratingCount:84},{name:"Amritsari Fish",price:490,category:"Mains",rating:4.7,ratingCount:56}])await db.execute({sql:"INSERT INTO menu_items (id, restaurant_id, name, price, category, rating, rating_count) VALUES (?, ?, ?, ?, ?, ?, ?)",args:[randomUUID(),restaurant.id,item.name,item.price,item.category,item.rating,item.ratingCount]});return restaurant}
export async function getRestaurantByOwner(ownerId:string){await ensure();const result=await db.execute({sql:"SELECT id, name, slug, description, theme FROM restaurants WHERE owner_id = ? ORDER BY created_at DESC LIMIT 1",args:[ownerId]});return result.rows[0] as unknown as {id:string;name:string;slug:string;description:string;theme:string}|undefined}
export async function getRestaurantBySlug(slug:string){await ensure();const result=await db.execute({sql:"SELECT id, name, slug, description, theme FROM restaurants WHERE slug = ?",args:[slug]});return result.rows[0] as unknown as {id:string;name:string;slug:string;description:string;theme:string}|undefined}
export async function getMenu(restaurantId:string){await ensure();const result=await db.execute({sql:"SELECT id,name,price,category,rating,rating_count FROM menu_items WHERE restaurant_id = ?",args:[restaurantId]});return result.rows as unknown as Array<{id:string;name:string;price:number;category:string;rating:number;rating_count:number}>}
export async function addOrder(restaurantId:string,customerName:string,total:number){await ensure();const id=`#${Math.floor(1000+Math.random()*9000)}`;await db.execute({sql:"INSERT INTO orders (id, restaurant_id, customer_name, total, status, created_at) VALUES (?, ?, ?, ?, 'NEW', ?)",args:[id,restaurantId,customerName,total,new Date().toISOString()]});return id}
